#!/usr/bin/env bash
#
# Lifecycle for the local SAP HANA, express edition instance.
#
#   ./hxe.sh init      generate a master password and seed it into the volume
#   ./hxe.sh start     bring the database up and wait until it accepts SQL
#   ./hxe.sh stop      stop the container, keeping the data volume
#   ./hxe.sh status    container state, uptime and memory
#   ./hxe.sh sql       open an interactive hdbsql session on the HXE tenant
#   ./hxe.sh logs      follow the container log
#   ./hxe.sh destroy   remove the container AND the data volume
#
# The credentials are generated, never committed. `init` writes them to
# hana/.hxe-credentials, which .gitignore excludes; every other script and the
# Python loader read them from there or from $HXE_MASTER_PASSWORD.
#
# Unlike HANA Cloud's free tier there is no nightly stop and no 30-day deletion
# rule, so there is nothing to restart on a schedule. `start` exists for the
# beginning of a working session, not as a survival mechanism.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CREDENTIALS="${HERE}/.hxe-credentials"
CONTAINER="novaspace-hxe"
VOLUME="novaspace-hxe-data"
TENANT_PORT=39017
READY_TIMEOUT_SECONDS=900

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m warn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

require_docker() {
  docker info >/dev/null 2>&1 || die "Docker is not responding. Start Docker Desktop and retry."
}

load_password() {
  if [[ -n "${HXE_MASTER_PASSWORD:-}" ]]; then
    printf '%s' "${HXE_MASTER_PASSWORD}"
    return
  fi
  [[ -f "${CREDENTIALS}" ]] || die "no credentials found. Run: ./hxe.sh init"
  # shellcheck disable=SC1090
  source "${CREDENTIALS}"
  printf '%s' "${HXE_MASTER_PASSWORD}"
}

generate_password() {
  # HANA requires >= 8 characters with upper, lower and a digit. Built from
  # three guaranteed classes plus random filler so it always satisfies the
  # policy rather than satisfying it by luck and failing one run in fifty.
  local filler
  filler="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 20)"
  printf 'Hxe%sQ7' "${filler}"
}

cmd_init() {
  require_docker

  if [[ -f "${CREDENTIALS}" ]]; then
    warn "credentials already exist at ${CREDENTIALS} - keeping them"
  else
    local password
    password="$(generate_password)"
    umask 077
    cat > "${CREDENTIALS}" <<EOF
# Generated by hxe.sh init. Local container only, synthetic data only.
# Excluded by .gitignore - do not commit, do not paste into documentation.
HXE_MASTER_PASSWORD='${password}'
HXE_HOST='localhost'
HXE_PORT='${TENANT_PORT}'
HXE_TENANT='HXE'
EOF
    log "wrote credentials to ${CREDENTIALS} (mode 600)"
  fi

  local password
  password="$(load_password)"

  log "seeding the master password into volume ${VOLUME}"
  docker volume create "${VOLUME}" >/dev/null
  # The password file has to live inside the volume, owned by hxeadmin (12000)
  # and unreadable by anyone else, or HANA refuses to start.
  printf '{"master_password":"%s"}' "${password}" \
    | docker run --rm -i -v "${VOLUME}:/hana/mounts" alpine:3 sh -c '
        cat > /hana/mounts/password.json
        chown 12000:79 /hana/mounts/password.json
        chmod 600 /hana/mounts/password.json
      '
  log "init complete. Next: ./hxe.sh start"
}

wait_until_ready() {
  local password deadline
  password="$(load_password)"
  deadline=$(( SECONDS + READY_TIMEOUT_SECONDS ))

  log "waiting for the HXE tenant to accept SQL (first boot takes several minutes)"
  while (( SECONDS < deadline )); do
    if docker exec "${CONTAINER}" bash -c \
         "/usr/sap/HXE/HDB90/exe/hdbsql -n localhost:${TENANT_PORT} -d HXE -u SYSTEM -p '${password}' -x 'SELECT 1 FROM DUMMY'" \
         >/dev/null 2>&1; then
      log "database is accepting connections on port ${TENANT_PORT}"
      return 0
    fi
    printf '.'
    sleep 15
  done
  printf '\n'
  die "tenant did not become ready within ${READY_TIMEOUT_SECONDS}s. Check: ./hxe.sh logs"
}

cmd_start() {
  require_docker
  [[ -f "${CREDENTIALS}" ]] || die "no credentials found. Run: ./hxe.sh init"

  local available_gb
  available_gb=$(docker info --format '{{.MemTotal}}' | awk '{printf "%.1f", $1/1073741824}')
  if awk -v m="${available_gb}" 'BEGIN{exit !(m < 8)}'; then
    warn "Docker has only ${available_gb} GB. HANA Express needs 8 GB minimum, 12 recommended."
    warn "Raise the WSL memory limit in %USERPROFILE%\\.wslconfig, or close applications."
  fi

  log "starting ${CONTAINER}"
  docker compose -f "${HERE}/docker-compose.yml" up -d
  wait_until_ready
  cmd_status
}

cmd_stop() {
  require_docker
  log "stopping ${CONTAINER} (data volume ${VOLUME} is kept)"
  docker compose -f "${HERE}/docker-compose.yml" stop
}

cmd_status() {
  require_docker
  if ! docker ps -a --format '{{.Names}}' | grep -qx "${CONTAINER}"; then
    echo "container: not created. Run: ./hxe.sh init && ./hxe.sh start"
    return 0
  fi
  docker ps -a --filter "name=${CONTAINER}" \
    --format 'container: {{.Names}}\nstate    : {{.State}}\nstatus   : {{.Status}}'
  docker stats --no-stream --format 'memory   : {{.MemUsage}} ({{.MemPerc}})' "${CONTAINER}" 2>/dev/null || true
  docker volume inspect "${VOLUME}" --format 'volume   : {{.Name}} at {{.Mountpoint}}' 2>/dev/null || true
}

cmd_sql() {
  require_docker
  local password
  password="$(load_password)"
  docker exec -it "${CONTAINER}" bash -c \
    "/usr/sap/HXE/HDB90/exe/hdbsql -n localhost:${TENANT_PORT} -d HXE -u SYSTEM -p '${password}' ${*:-}"
}

cmd_logs() {
  require_docker
  docker logs -f --tail 200 "${CONTAINER}"
}

cmd_destroy() {
  require_docker
  warn "this removes the container AND the data volume ${VOLUME}."
  warn "Every loaded table and deployed view is lost. Sources in Git are not."
  read -r -p "Type the volume name to confirm: " confirmation
  [[ "${confirmation}" == "${VOLUME}" ]] || die "not confirmed - nothing was removed"
  docker compose -f "${HERE}/docker-compose.yml" down -v
  log "removed. Rebuild with: ./hxe.sh init && ./hxe.sh start && python hana/load_data.py"
}

case "${1:-}" in
  init)    cmd_init ;;
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  status)  cmd_status ;;
  sql)     shift; cmd_sql "$@" ;;
  logs)    cmd_logs ;;
  destroy) cmd_destroy ;;
  *)
    sed -n '3,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
    ;;
esac
